### ISSUE TITLE
I see you got a set of torrent scrapers ! 

### ISSUE THREAD

**Issue by SerpentDrago** [ventsislav-georgiev/btScraper#1]
Can i ask what all fix's you did to them vs the a4k ones ?  /r/addons4kodi

We were working on some fix's ourselfs (a4k and friends ) .

Just curious . without me downloading and diff'ing them

**Comment by ventsislav-georgiev** [comment]
The repo is based on the a4k, but I have rewritten them. I've made the maintenance of the individual sites easier by extracting all base code to utility class and leaving only the DOM filtration in the separate files. With this change the queries for episodes are also shared see [here](https://github.com/ventsislav-georgiev/btScraper/blob/master/providers/btScraper/en/torrent/lib/t_utils.py#L193). As for the sites, for me katcr was not working at all and I've updated it to not use the advanced search endpoints. I've also added yourbittorrent2 and zooqle. There were changes to the others also, as I said they are rewritten.

**Comment by SerpentDrago** [comment]
Holy hell man , thats impressive work !

**Comment by SerpentDrago** [comment]
Can i just drop them in the right folder / and test them out ? or does it require any changes you made to Seren .

I get i would need that PR for Seren if i wanted to install though URL / Zip , but just directly installing the zip or putting  the files in the correct place manually  still works fine right ?

**Comment by SerpentDrago** [comment]
Do you have telegram ? I'd like to chat if you could @SerpentDrago  on Telegram

**Comment by SerpentDrago** [comment]
just reziped it without the folder (root directory)  Testing now  .
